#! /bin/sh

# PROVIDE: testtool
# KEYWORD: nojail
# REQUIRE: NETWORKING LOGIN bird bird6 iglb

. /etc/rc.subr

name="testtool"
rcvar=${name}_enable
reload_cmd="service testtool restart"
downtimes_cmd="downtimes_cmd"
extra_commands="reload downtimes"
start_postcmd="start_postcmd"

: ${testtool_enable:="NO"}

pidfile="/var/run/${name}_daemon.pid"
pidfile_testtool="/var/run/${name}_testtool.pid"

command="/usr/local/sbin/testtool"
procname="/usr/sbin/daemon"
start_cmd="${procname} -r -P ${pidfile} -p ${pidfile_testtool} -f -c ${command}"

load_rc_config $name

start_postcmd() {
	# Allow the iglb user to read the pidfile and thus to trigger
	# downtime-only config reload.
	chown root:iglb $pidfile_testtool
	chmod 640 $pidfile_testtool
}

downtimes_cmd() {
	pid_testtool=$(check_pidfile $pidfile_testtool $command)
	if [ -z "$pid_testtool" ]; then
		echo "$command is not running!"
		exit 1
	else
		echo "Reloading downtimes"
		kill -USR1 $pid_testtool
	fi
}

run_rc_command "$1"
