#! /bin/sh

# PROVIDE: ig.testtool
# KEYWORD: nojail
# REQUIRE: NETWORKING LOGIN bird bird6 iglb

. /etc/rc.subr

name=testtool
rcvar=testtool_enable
start_cmd="testtool_start"
stop_cmd="testtool_stop"
reload_cmd="testtool_reload"
status_cmd="testtool_status"
extra_commands="reload status"

load_rc_config "${name}"

testtool_start() {
	echo "Starting testtool"
	if pgrep -f "/bin/sh /usr/local/sbin/testtool_watchdog" > /dev/null; then
		echo "testtool_watchdog already running"
	else
		/usr/local/bin/screen -dmS testtool /usr/local/sbin/testtool_watchdog
	fi
}

testtool_stop() {
	echo -n "Stopping testtool_watchdog"
	while pkill -f '^/bin/sh /usr/local/sbin/testtool_watchdog$'; do
		echo -n "."
		sleep 1
	done
	echo
	echo "There were no survivors"  

	echo -n "Stopping testtool"
	while pkill -f '^/usr/local/sbin/testtool(.testing)?$'; do
		echo -n "."
		sleep 1
	done
	echo
	echo "There were no survivors"  
}

testtool_reload() {
	echo Gracefuly reloading testtool
	pkill -HUP -f '^/usr/local/sbin/testtool(.testing)?$' 
}

testtool_status() {
	# Testtool might be restarting at the moment.
	cnt=6
	while [ "$cnt" -gt 0 ]; do
		cnt=$((cnt-1))
        echo "Waiting for testtool..."
		pid=`pgrep -f '^/usr/local/sbin/testtool(.testing)?$'`
		if [ "$?" -eq 0 ]; then
			echo ${name} is running as pid $pid
			exit 0
		fi
		sleep 1
	done
	
	echo ${name} is not running!
	exit 1
}

run_rc_command "$1"

